### ISSUE TITLE
Error to Quick Start in W10

### ISSUE THREAD

**Issue by eder-toledo** [vuetifyjs/vue-cli-plugin-vuetify#40]
### **Versions** and Environment

Package.son contain
    "@babel/polyfill": "^7.0.0-rc.1",
    "vue": "^2.5.17",
    "vuetify": "^1.2.0"

OS: Windows 10

Node version: v8.12.0

Npm version: 6.4.1

### **Steps** to reproduce

Quick start: https://vuetifyjs.com/en/getting-started/quick-start
npm install @vue/cli -g
![imagen](https://user-images.githubusercontent.com/2104229/45794160-ee8b8680-bc5a-11e8-8948-56965be0a72b.png)
![imagen](https://user-images.githubusercontent.com/2104229/45794179-0105c000-bc5b-11e8-984f-8a639d72b601.png)

vue create my-app
![imagen](https://user-images.githubusercontent.com/2104229/45794186-0bc05500-bc5b-11e8-9278-70f28f048a40.png)

vue add vuetify
![imagen](https://user-images.githubusercontent.com/2104229/45794201-1e3a8e80-bc5b-11e8-99e9-548f045f31a5.png)

npm run serve
![imagen](https://user-images.githubusercontent.com/2104229/45794224-3ca08a00-bc5b-11e8-9637-c84c1550fda8.png)

### **Actual** Behavior
Failed to compile with 1 error

![imagen](https://user-images.githubusercontent.com/2104229/45794246-5510a480-bc5b-11e8-8e5d-518a2f73833a.png)

**Comment by jacekkarczmarczyk** [comment]
The error message is quite descriptive so maybe we're able to do something about it (you can remove .browserslistrc file or browsers list section from package.json), but I'm not able to reproduce it, when I run `vue create my-app` i'm getting a bit different output

![image](https://user-images.githubusercontent.com/15625235/45800370-05f55e80-bcb1-11e8-8445-886c501f04e1.png)

As you can see I'm chosing here the preset, I don't see it in your screen shot and I don't know what preset has been selected, can you give more information?

**Comment by tobynet** [comment]
I have the same issue.

I consider that this issue caused by the followings.

* `browserlist` v3.2.x do not allow config in both `.browserslistrc` and `package.json`. [🔗1][1]
* `vue-cli` v3, `@vue/cli-service` add config to `package.json`. [🔗2][2]

   🤔 I think many users use its plugin with `vue create`.

* This plugin, `vue-cli-plugin-vuetify`, add config to `.browserslistrc`. [🔗3][3]

📝 browserlist v3, or later, recommend adding the config to `package.json`.   [🔗4][4]

> browserslist key in package.json file in current or parent directories. We recommend this way.  

## An ad-hoc solution **FOR USERS**

1. Modify `package.json` referenced by `.browserslistrc`.

    e.g.
    ```diff
    --- a/package.json
    +++ b/package.json
    @@ -41,6 +41,6 @@
    "browserslist": [
        "> 1%",
        "last 2 versions",
    -    "not ie <= 8"
    +    "not ie <= 10"
    ]
    }
    ```
2. Delete `.browserslistrc`.
3. Fix it in your local project.

[1]: https://github.com/browserslist/browserslist/blob/3.2.8/test/config.test.js#L98-L102
[2]: https://github.com/vuejs/vue-cli/blob/v3.0.3/packages/%40vue/cli-service/generator/index.js#L20-L24
[3]: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/v0.2.0/generator/tools/polyfill.js#L35-L54
[4]: https://github.com/browserslist/browserslist/blob/3.2.8/README.md#queries

**Comment by eder-toledo** [comment]
> 
> 
> I have the same issue.
> 
> I consider that this issue caused by the followings.
> 
>     * `browserlist` v3.2.x do not allow config in both `.browserslistrc` and `package.json`. [🔗1](https://github.com/browserslist/browserslist/blob/3.2.8/test/config.test.js#L98-L102)
> 
>     * `vue-cli` v3, `@vue/cli-service` add config to `package.json`. [🔗2](https://github.com/vuejs/vue-cli/blob/v3.0.3/packages/%40vue/cli-service/generator/index.js#L20-L24)
>       🤔 I think many users use its plugin with `vue create`.
> 
>     * This plugin, `vue-cli-plugin-vuetify`, add config to `.browserslistrc`. [🔗3](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/v0.2.0/generator/tools/polyfill.js#L35-L54)
> 
> 
> 📝 browserlist v3, or later, recommend adding the config to `package.json`. [🔗4](https://github.com/browserslist/browserslist/blob/3.2.8/README.md#queries)
> 
> > browserslist key in package.json file in current or parent directories. We recommend this way.
> 
> ## An ad-hoc solution **FOR USERS**
> 
>     1. Modify `package.json` referenced by `.browserslistrc`.
>        e.g.
>        ```diff
>        --- a/package.json
>        +++ b/package.json
>        @@ -41,6 +41,6 @@
>        "browserslist": [
>            "> 1%",
>            "last 2 versions",
>        -    "not ie <= 8"
>        +    "not ie <= 10"
>        ]
>        }
>        ```
> 
>     2. Delete `.browserslistrc`.
> 
>     3. Fix it in your local project.

He performed the recommended steps and it worked, thanks for the help.

**Comment by johnleider** [comment]
This should be resolved now.
